previous error whereby mysql package was not allowing me to import userService is gone
past error was:

Error: ER_NOT_SUPPORTED_AUTH_MODE

Client does not support authentication protocol requested by server; consider upgrading MySQL client

But it is no longer there, so I am using mysql package due to bug with mysql2 and jest